### ISSUE TITLE
Include event date/time in notification

### ISSUE THREAD

**Issue by dkadioglu** [nickv-nextcloud/event_update_notification#10] opened 2019-03-27 17:06 UTC
It would be great to have date/time of the event in the notification. Otherwise additional effort is necessary to find the mentioned event in the calendar. I am not sure, if this is something relevant for this app or nextcloud itself, though.

**Comment by nickvergessen** [comment] 2019-03-27 17:52
It can not be added to the push notification at the moment. But when you click on the notification which opens the notification overview the time and date of the events are displayed.

**Comment by dkadioglu** [comment] 2019-03-28 06:38
OK, thank you very much for your reply. Could you elaborate a bit on that, please? Is it the fault of nextclouds notification system or of this app? What is missing from your point of view?
Another question: Is it possible to integrate date/time of the event in the email nextcloud sends in case of new notifications?

**Comment by nickvergessen** [comment] 2019-03-28 08:53
It's the fault of the maximum characters allowed in a push notification.by google and apple and us encrypting the message so they can not read the notifications.

Which email exactly are you talking about?

**Comment by dkadioglu** [comment] 2019-03-28 11:12
Oh, maybe there is a misunderstanding on my side? Actually I meant the notifications in the nextcloud web interface (the bell in the top right part). In the nextcloud user profile it can then be configured to inform the user about new notifications via email. I hope, this makes it more clear.

**Comment by hillbicks** [comment] 2019-11-06 23:23
Since it is a long time since there was an update on this topic, I'd like to give my two cents as well. I'm using this feature to send out email notifications when someone makes changes to a shared calendar. 

The problem is that the email does not contain the date and time of the event, so I either have to ask the corresponding user or search the calendar for it. So it would be nice to at least have an option to enable this for the email notifications since the push notification seems to be limited by the amount of characters. 

Would that be feasible?

**Comment by dkadioglu** [comment] 2019-11-07 14:41
@hillbicks Thank you for your perfect description of the issue. I would also second the idea of having the possibility to include date and time in the notification email.

**Comment by nickvergessen** [comment] 2019-11-07 15:26
This app has nothing to do with any emails being sent.

**Comment by kesselb** [comment] 2019-11-07 17:10
![](https://github.com/nickv-nextcloud/event_update_notification/raw/master/docs/demo.png)

@dkadioglu @hillbicks your request is about "Admin updated event TestEventUpdated in calendar TestCalendar" right? It should be something like "Admin updated event TestEventUpdated (2019-11-07 18:00) in calendar TestCalendar"

**Comment by hillbicks** [comment] 2019-11-07 17:27
Yes, that's exactly it!. And I just realised that this plugin is really not the correct place for this. 

How did you manage to include the date/time in the screenshot @kesselb

**Comment by dkadioglu** [comment] 2019-11-07 17:45
Exactly that!! I would also like to know, how you managed to do that. And does that information also appear in the email notification Nextcloud can send?

**Comment by kesselb** [comment] 2019-11-07 17:48
> How did you manage to include the date/time in the screenshot

It's the screenshot of the app from [GitHub](https://github.com/nickv-nextcloud/event_update_notification/blob/master/docs/demo.png) ;)

**Comment by dkadioglu** [comment] 2019-11-07 17:51
ah, ok. now I realize that the notification indeed contains that information but, the item in the activity stream does not. also, the email sent by nextcloud does not. I opened an issue for that in nextcloud/activity: https://github.com/nextcloud/activity/issues/403

**Comment by hillbicks** [comment] 2019-11-07 18:24
@dkadioglu: Thanks for that, I'll give you a thumbs up on the other thread.

@nickvergessen: Sorry for the confusion, I think you can close this issue here.

**Closed as completed** 2019-11-07 19:41 UTC

**Comment by FredMa01** [comment] 2021-02-27 17:31
> 
> 
> ah, ok. now I realize that the notification indeed contains that information but, the item in the activity stream does not. also, the email sent by nextcloud does not. I opened an issue for that in nextcloud/activity: https://github.com/nextcloud/activity/issues/403

No answer.  It seems to be difficult to include the date/time in nextcloud activity...
